spring:
  datasource:
    url: jdbc:mysql://localhost:3306/person?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs


